### ISSUE TITLE
master branch and 1.5 do not compile with casacore 3.2.1

### ISSUE THREAD

**Issue by sarrvesh** [casacore/casarest#33]
When I build casarest, I get the following error:

/casarest/msvis/MSVis/VisibilityIterator.h:35:10: fatal error: casacore/casa/Containers/Stack.h: No such file or directory
 #include <casacore/casa/Containers/Stack.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

I get the same error when I build with casarest 1.5.0.

Could you please have a look?

**Comment by sarrvesh** [comment]
I see this is the same issue as issue #29 . I'll close this ticket. Apologies for the noise.

**Comment by bennahugo** [comment]
See #31
