### ISSUE TITLE
1.5.0 doesn't compile with casacore 3.1.1

### ISSUE THREAD

**Issue by AlexKurek** [casacore/casarest#29]
I have tried under Ubuntu 18.04.2 in order to use it as one of the LOFARs software 4.0.2 requirements. It does not compile.

Best regards,
Alex

**Comment by gijzelaerr** [comment]
what is the error

**Comment by gijzelaerr** [comment]
You could try if it works with the open PR in the repo. If it does we probably should merge it and make a new release.

**Comment by AlexKurek** [comment]
> what is the error

The error is:

> [ 28%] Building CXX object components/SpectralComponents/test/CMakeFiles/tSpectralFit.dir/tSpectralFit.cc.o
> In file included from /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.h:174:0,
>                  from /opt/casarest/src/components/SpectralComponents/SpectralFit2.tcc:39,
>                  from /opt/casarest/src/components/SpectralComponents/SpectralFit.h:179,
>                  from /opt/casarest/src/components/SpectralComponents/test/tSpectralFit.cc:39:
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc: In member function ‘T casacore::CompiledFunction<T>::eval(typename casacore::Function<T>::FunctionArg) const [with T = casacore::AutoDiff<double>]’:
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc:153:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
>        if (pos->state.argcnt == 1) {
>        ^~
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc:157:5: note: here
>      case FuncExprData::ATAN2:
>      ^~~~
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc: In member function ‘T casacore::CompiledFunction<T>::eval(typename casacore::Function<T>::FunctionArg) const [with T = double]’:
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc:153:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
>        if (pos->state.argcnt == 1) {
>        ^~
> /opt/casacore/include/casacore/scimath/Functionals/CompiledFunction.tcc:157:5: note: here
>      case FuncExprData::ATAN2:
>      ^~~~
> [ 28%] Linking CXX executable tSpectralFit
> [ 28%] Built target tSpectralFit
> [ 28%] Building CXX object msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o
> In file included from /opt/casarest/src/msvis/MSVis/VisBuffer.h:39:0,
>                  from /opt/casarest/src/msvis/MSVis/CalVisBuffer.h:32,
>                  from /opt/casarest/src/msvis/MSVis/CalVisBuffer.cc:28:
> **/opt/casarest/src/msvis/MSVis/VisibilityIterator.h:35:10: fatal error: casacore/casa/Containers/Stack.h: No such file or directory**
>  #include <casacore/casa/Containers/Stack.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> msvis/CMakeFiles/casa_msvis.dir/build.make:75: recipe for target 'msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o' failed
> make[2]: *** [msvis/CMakeFiles/casa_msvis.dir/MSVis/CalVisBuffer.cc.o] Error 1
> CMakeFiles/Makefile2:2092: recipe for target 'msvis/CMakeFiles/casa_msvis.dir/all' failed
> make[1]: *** [msvis/CMakeFiles/casa_msvis.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by gijzelaerr** [comment]
Ok PR 28 is supposed to fix casacore 3.1 support, so that makes sense. Please use that branch until we merge this. the build system needs an update also.

I'm going to

**Comment by AlexKurek** [comment]
(Just FYI, LOFARsoft 4.0.2 does not compile using casacore 3.1.2, so probably LOFARsoft users still have to use casacore 3.1)

**Comment by gijzelaerr** [comment]
Did you report that issue? @tammojan are you aware of this?

**Comment by AlexKurek** [comment]
> Did you report that issue?

Yes, I reported it at ther SOS e-mail.
The error message is below.


> [ 19%] Building CXX object CEP/ParmDB/src/CMakeFiles/parmdb.dir/ParmDBLog.cc.o
> In file included from /opt/lofar/src/CEP/ParmDB/src/ParmDBLog.cc:24:0:
> /opt/lofar/build/gnucxx11_cep4_optarch/include/ParmDB/ParmDBLog.h:33:10: fatal error: casacore/casa/Containers/Map.h: No such file or directory
>  #include <casacore/casa/Containers/Map.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CEP/ParmDB/src/CMakeFiles/parmdb.dir/build.make:398: recipe for target 'CEP/ParmDB/src/CMakeFiles/parmdb.dir/ParmDBLog.cc.o' failed
> make[2]: *** [CEP/ParmDB/src/CMakeFiles/parmdb.dir/ParmDBLog.cc.o] Error 1
> CMakeFiles/Makefile2:1902: recipe for target 'CEP/ParmDB/src/CMakeFiles/parmdb.dir/all' failed
> make[1]: *** [CEP/ParmDB/src/CMakeFiles/parmdb.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by tammojan** [comment]
Thanks for reporting, I reported it to https://support.astron.nl/rohelpdesk as well, not sure the sos email is still read.

**Comment by AlexKurek** [comment]
> not sure the sos email is still read

They do, they just responded

Alex

**Comment by AlexKurek** [comment]
It compilled with -DBUILD_DEPRECATED=True in casacore 3.1.2

**Comment by tammojan** [comment]
Should be solved by #31.
